[workspace]
members = ["common", "books_api", "books_analytics", "database"]

[workspace.dependencies]
tokio = { version = "1.28.2", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3"